### PR TITLE
implemented the docker-compose setup

### PR DESCRIPTION
**Pull request by mihrab34**
Added the docker-compose.yml file which include docker container set-up for the main cubeseed and the database based on issue #32 

docker-compsoe

### CODE REVIEW

**Comment by sgarciahelguera** [comment]
Have you tried it?
DJango is not yet configured to point to an external database service, so the second container won't be used for now.
I haven't had the time to read about this yet, but I think the advantage for us would be if it has an auto update setting. I am not sure how should that setting look but it doesn't seem to be any update related setting in the file.
Also I think this file should point to the docker file, there is probably an option to set it.

**Review by sgarciahelguera — APPROVED** [review]
you can remove the database container, or leave it...
it is not being used but we should add it to django for production (see #5 )

**Comment by sgarciahelguera** [comment]
I think the correct issue for this is #26

**Comment by sgarciahelguera** [comment]
Should we merge this ? or will you remove the db container settings? 
I think removing those is better but no big difference (we will need to add those at some ponit)

**Comment by mihrab34** [comment]
> Should we merge this ? or will you remove the db container settings? I think removing those is better but no big difference (we will need to add those at some ponit)

I can see it's approved, I'll merge it and also include the screenshot i mentioned during the meeting

**Pull request merged**
