### PR TITLE
Add farmerprofile

### PR DESCRIPTION
**Pull request by shawnkoong**
For issue #15 

This adds a model for FarmerProfile as well as a FileDescriptor class (class name for File already exists) and one that inherits this for course certificates.

### CODE REVIEW

**Comment by mihrab34** [comment]
Hi @shawnkoong  Great work! Can you also include a unit test for the farmerprofile. Thanks.

**Comment by sgarciahelguera** [comment]
Looks good, I agree with @mihrab34 that we need to add tests though.
I'll try to add code coverage action with some requirement as soon as possible.

**Comment by sgarciahelguera** [comment]
Added coverage check action https://github.com/Cubeseed/Backend/pull/36 
Maybe we can merge that and check how this works, coverage is showing a really high percentage, so it would be great to check how it behaves here.

**Comment by abu-hasib** [comment]
Can I get the link to the hosted API

**Comment by mihrab34** [comment]
> Added coverage check action #36 Maybe we can merge that and check how this works, coverage is showing a really high percentage, so it would be great to check how it behaves here.

Yeah , we can merge it. You'll have to approve the review though

**Comment by sgarciahelguera** [comment]
This looks stuck, should we close it? 
@shawnkoong were you able to merge main into this and add some tests? do you need help?

**Review by mihrab34 — APPROVED** [review]
we can merge this

**Pull request merged**
