### PR TITLE
Choose course Api and course verification

### PR DESCRIPTION
**Pull request by jMkwendy45**
In the absence of the external third-party link to the course. I created model class called Course which properties include title, link etc. This link will contain the external thirdparty url. Please review and share feedback.  For course verification, I added assigned_code to the UserProfile, this is the code we use to check against the code the user will input alongside the certificate during course verification.

### CODE REVIEW

**Comment by sgarciahelguera** [comment]
Maybe @mihrab34 can give you a hand with this before monday (I'll be on it then).
It looks like you are adding a folder that looks very local to your setup (`OneDrive/Desktop/cubeseed2`) and it looks like it has configuration in xml for `idea` (is that for vscode? we have settings for vscode in json files under `.vscode` folder.
I am not sure I understand this Pull request, but from my first look I think you made a pr for a repository in a containing folder of this repo.
I mean you have a git project in your `OneDrive` local folder and you are trying to merge that when you should be trying to merge the git project for this repository, that may be in your `cubeseed2` local folder (but I'm guessing here, no idea what you have in that folder).
But for sure there is no python code in this PR.

**Comment by mihrab34** [comment]
Hi @jMkwendy45  I also can't find the changes you made. Perhaps we can get on a call together to take a look at the issue. Did you fork the repository?

**Comment by jMkwendy45** [comment]
Yes i did fork the re

> Hi @jMkwendy45 I also can't find the changes you made. Perhaps we can get on a call together to take a look at the issue. Did you fork the repository?

y

**Comment by jMkwendy45** [comment]
yes i did fork the repository,i would appreciate it if we can do it over a call,thank

**Comment by mihrab34** [comment]
What's your discord username so i can send you a google meet link

**Comment by mihrab34** [comment]
@sgarciahelguera this pull request is closed as there was some issue with her local branch. The changes you mentioned above have been made in #41

**Pull request closed without merging**
