### PR TITLE
Task #7: I want approval messages and notifications

### PR DESCRIPTION
**Pull request by n1klaus**
Progress:
1. Setup  for sending approval/rejection email.  
2. Handle the jobs in queues using celery job queues 
3. Add tests
4. Connect with existing frontend and add more tests

### CODE REVIEW

**Comment by n1klaus** [comment]
#63 Adds email notifications for the user with job status tracking and logging

**Comment by sgarciahelguera** [comment]
Can you checkout the conflicts? 
do you have access to create branches ? (i have some issue on github actions when working form a fork, I can ignore that and force the merge, but try to use a branch in the future)

**Comment by sgarciahelguera** [comment]
I looked over this , I am not sure about the black package and I think the environment management is better the way was handled for AWS file storage variables, but I can change that on my pr (I have to go over all settings anyway)

**Comment by n1klaus** [comment]
Let me try to fix it

**Pull request closed without merging**
