### PR TITLE
fix merge conflict

### PR DESCRIPTION
**Pull request by jMkwendy45**

### CODE REVIEW

**Comment by sgarciahelguera** [comment]
I think the OneDrive folder does not belong to the repository, you are adding it again.

**Comment by sgarciahelguera** [comment]
@jMkwendy45  This looks stuck, do you need help? should we close this?

**Comment by jMkwendy45** [comment]
i need help ,you can close it thank you

**Comment by sgarciahelguera** [comment]
We don't need to delete this if you are still active/working on it.
If you need help removing the OneDrive directory checkout: https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste

**Comment by sgarciahelguera** [comment]
About the conflicts showing up seem to be just changes in main, just do a `git fetch` and `git merge origin/main`
Then the conflict will show up locally in your setup.
To resolve the conflict you need to edit the files merging the code marked with <<<<<< ===== and >>>>> 
For example:
```
<<<<<<< master
from cubeseed.userauth.serializers import UserSerializer, GroupSerializer, RegisterUserSerializer, CourseSerializer

from Backend.cubeseed.userauth.models import Course
=======
from rest_framework.views import APIView
from rest_framework.response import Response
from cubeseed.userauth.serializers import UserSerializer, GroupSerializer, RegisterUserSerializer
from cubeseed.settings import VERSION
>>>>>>> main
```

Should end up being something like (the changes you meant originally, but now on top of the "new" baseline):

```
from rest_framework.views import APIView
from rest_framework.response import Response
from cubeseed.userauth.serializers import UserSerializer, GroupSerializer, RegisterUserSerializer
from cubeseed.userauth.serializers import UserSerializer, GroupSerializer, RegisterUserSerializer, CourseSerializer
from cubeseed.userauth.models import Course
from cubeseed.settings import VERSION
```

**Comment by jMkwendy45** [comment]
alright thank you

**Comment by sgarciahelguera** [comment]
Any progress on this @jMkwendy45  ? 
Could you add some description to the PR and link an issue to it ? (either an existing issue or create one)

**Comment by sgarciahelguera** [comment]
I'm closing this while there are no news, just reopen if there is any progress

**Pull request closed without merging**
